server:
  port: 9000

eureka:
  instance:
    hostname: ribbon-service
  client:
    serviceUrl:
      defaultZone: http://peer1:8081/eureka/

spring:
  application:
    name: ribbon-service

# 代码 + 配置文件配置方式
#service-1:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule